title: Swishhyys Custom Items (SCI)
description: Documentation for the Swishhyys Custom Items plugin for SCP:SL
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Site settings
url: "" # Will be set when published on GitHub Pages
baseurl: "/SCI"

# GitHub metadata
github:
  is_project_page: true
  repository_url: https://github.com/Swishhyy/SCI

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/