title: SCI Documentation
description: Documentation for Swishhyys Custom Items (SCI)
theme: jekyll-theme-primer
baseurl: "/SCI"
url: "https://swishhyy.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_docs"
      type: docs
    values:
      layout: page

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - .git/

sass:
  style: compressed
  sass_dir: _sass