name: Build .NET Framework EXILED Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            **/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore NuGet Packages
        run: nuget restore SCI.sln

      - name: Build Solution
        run: msbuild SCI.sln /m /p:Configuration=Release

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: exiled-plugin-dlls
          path: '**\bin\Release\*.dll'
