name: Build .NET Framework EXILED Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Cache NuGet packages to speed up subsequent builds
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          # The common NuGet package folder on Windows and in some cases the project's packages folder
          path: |
            ~/.nuget/packages
            **/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Step 3: Restore NuGet dependencies using the NuGet CLI
      - name: Restore NuGet Packages
        run: nuget restore SCI.sln

      # Step 4: Build the solution using MSBuild
      - name: Build Solution
        run: msbuild SCI.sln /m /p:Configuration=Release

      # Step 5: (Optional) Upload the compiled DLLs as an artifact so you can download them if needed
      - name: Upload Compiled DLLs
        uses: actions/upload-artifact@v3
        with:
          name: exiled-plugin-dlls
          path: '**\bin\Release\*.dll'
