name: Nightly Build - Exiled Plugin

on:
  schedule:
    - cron: '0 0 * * *' # Runs nightly at midnight UTC
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            **/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore NuGet Packages
        run: nuget restore ./SCI.sln

      - name: Build Solution
        run: |
          REM Use MSBuild to build the solution
          "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe" ./SCI.sln /m /p:Configuration=Release
        shell: cmd

      - name: Upload Compiled Artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Exiled-Plugin-Nightly
          path: '**\bin\Release\*.dll'
