name: Nightly Build - Exiled Plugin

on:
  schedule:
    - cron: '0 0 * * *' # Runs nightly at midnight UTC
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache NuGet Packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            **/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Validate Solution File
        run: |
          if not exist "./SCI.sln" (
            echo "Error: Solution file (SCI.sln) is missing." && exit 1
          )
        shell: cmd

      - name: Restore NuGet Packages
        run: nuget restore ./SCI.sln
        shell: cmd
        timeout-minutes: 10

      - name: Include External Dependencies
        run: |
          mkdir -p ./bin/ExternalDependencies
          cp -r ExternalDependencies/* ./bin/ExternalDependencies
        timeout-minutes: 10

      - name: Build Solution
        run: |
          for /f "tokens=*" %%i in ('"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe') do set MSBUILD_PATH=%%i
          "%MSBUILD_PATH%" ./SCI.sln /m /p:Configuration=Release
        shell: cmd
        timeout-minutes: 15

      - name: Verify Build Output
        run: |
          if not exist "**\\bin\\Release\\*.dll" (
            echo "Error: Build artifacts are missing in Release directory." && exit 1
          )
        shell: cmd

      - name: Upload Compiled Artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Exiled-Plugin-Nightly
          path: '**\\bin\\Release\\*.dll'

      - name: Clean Up Cache (Optional)
        run: |
          echo "Cleaning up cache to avoid stale artifacts..."
          del /q /s **\\bin\\Release\\*.dll
        shell: cmd


       
